# -*- coding: utf-8 -*-

# Copyright (c) 2023 tecnovert
# Copyright (c) 2024-2025 The Basicswap developers
# Distributed under the MIT software license, see the accompanying
# file LICENSE or http://www.opensource.org/licenses/mit-license.php.

from basicswap.interface.btc import (
    BTCInterface,
)
from basicswap.chainparams import Coins

class NAVInterface(BTCInterface):
    @staticmethod
    def coin_type() -> Coins: # type: ignore[override]
        return Coins.NAV

    def __init__(self, coin_settings, network, swap_client=None):
        super(NAVInterface, self).__init__(coin_settings, network, swap_client)

    def initialiseWallet(self, key_bytes, restore_time: int = -1):
        del restore_time
        #key_wif = self.encodeKey(key_bytes)
        # TODO NAV remove this
        key_wif = "322cf308b2a883ce247514be112afdb64c71c562f6ed16d0a8d83ed00f33b306"
        try:
            self.rpc_wallet("setblsctseed", [key_wif])
        except Exception as e:
            self._log.debug(f"setblsctseed failed: {e}")
            raise (e)

    def getSeedHash(self, seed: bytes) -> bytes:
        del seed
        seedid_hex = self.getWalletSeedID()
        return bytes.fromhex(seedid_hex)

    def getWalletSeedID(self) -> str:
        """
        The Navio wallet has been initialized using the root key generated by
        `getWalletKey(c, 1)` as the seed.
        """
        wi = self.rpc_wallet("getwalletinfo")
        return wi["hdseedid"]

    def checkExpectedSeed(self, expect_seedid: str) -> bool:
        actual_seedid = self.getWalletSeedID()
        return expect_seedid == actual_seedid

    def getNewAddress(self, use_segwit: bool, label: str = "swap_receive") -> str:
        del use_segwit
        return "tnv14adxpa06t5fywwtte3g223ef92plxqm7ls2jxqp5rwef2cz7ppdhx36ck0e42x2dkj92vw3kxfj90zpzy8ymnmqd9x9gc5wq2xv6m5rkxcxz39jpvaan4dw254ayl94h5tuy5pftaczhcrr5exz9ke0cdgr75y6ft5"
        # address: str = self.rpc(
        #     "getnewaddress",
        #     [
        #         label,
        #         "blsct",
        #     ],
        # )
        # return address

