# -*- coding: utf-8 -*-

# Copyright (c) 2023 tecnovert
# Copyright (c) 2024-2025 The Basicswap developers
# Distributed under the MIT software license, see the accompanying
# file LICENSE or http://www.opensource.org/licenses/mit-license.php.

# from io import BytesIO
# from coincurve.keys import (
#     PublicKey,
#     PrivateKey,
# )
from basicswap.interface.btc import (
    BTCInterface,
    # extractScriptLockRefundScriptValues,
    # findOutput,
    # find_vout_for_address_from_txobj,
)
from basicswap.rpc import make_rpc_func
from basicswap.chainparams import Coins
# from basicswap.contrib.mnemonic import Mnemonic
# from basicswap.interface.contrib.nav_test_framework.mininode import (
#     CTxIn,
#     CTxOut,
#     CBlock,
#     COutPoint,
#     CTransaction,
#     CTxInWitness,
#     FromHex,
# )
#from basicswap.util.crypto import hash160
# from basicswap.util.address import (
#     decodeWif,
#     pubkeyToAddress,
#     encodeAddress,
# )
# from basicswap.util import (
#     b2i,
#     i2b,
#     ensure,
# )
# from basicswap.basicswap_util import (
#     getVoutByScriptPubKey,
# )
#
# from basicswap.interface.contrib.nav_test_framework.script import (
#     CScript,
#     OP_0,
#     OP_EQUAL,
#     OP_DUP,
#     OP_HASH160,
#     OP_EQUALVERIFY,
#     OP_CHECKSIG,
#     SIGHASH_ALL,
#     SegwitVersion1SignatureHash,
# )
#

class NAVIOInterface(BTCInterface):
    @staticmethod
    def coin_type() -> Coins: # type: ignore[override]
        return Coins.NAVIO

    def __init__(self, coin_settings, network, swap_client=None):
        super(NAVIOInterface, self).__init__(coin_settings, network, swap_client)

    def initialiseWallet(self, key_bytes, restore_time: int = -1):
        del restore_time
        key_wif = self.encodeKey(key_bytes)
        try:
            self.rpc_wallet("setblsctseed", [key_wif])
        except Exception as e:
            self._log.debug(f"setblsctseed failed: {e}")
            raise (e)

    def getSeedHash(self, seed: bytes) -> bytes:
        del seed
        seedid_hex = self.getWalletSeedID()
        return bytes.fromhex(seedid_hex)

    def getWalletSeedID(self) -> str:
        """
        The Navio wallet is initialized using the root key generated by
        `getWalletKey(c, 1)` as the seed.
        """
        wi = self.rpc_wallet("getwalletinfo")
        return wi["hdseedid"]

    def checkExpectedSeed(self, expect_seedid: str) -> bool:
        actual_seedid = self.getWalletSeedID()
        return expect_seedid == actual_seedid

    def getNewAddress(self, use_segwit: bool, label: str = "swap_receive") -> str:
        del use_segwit
        address: str = self.rpc(
            "getnewaddress",
            [
                label,
                "blsct",
            ],
        )
        return address

